### ISSUE TITLE
Stuck at the top of the beam

### ISSUE THREAD

**Issue by 1d10t-Gaming** [dawson-vilamaa/BeaconWaypoints#1]
So I downloaded the Beacon Waypoints plug in and I made a spawn waypoint and a shopping district waypoint, I went to the shopping district one and it worked fine and let me tell you, that is the coolest thing I've ever seen, but when I tried to go back to spawn it would just teleport me 580 blocks in the air (like it should) and I would fall maybe 40ish blocks and it would teleport me back up, and it would be in a loop, and the only way I could get out is if I did /reload, and tried it again, and again, and it did the same thing

I was in creative mode (not flying) so maybe I need to be in survival for it to work? 

I would like to reinstall this back onto my server, as of right now I have a sign that if right clicked, it tps you there (really boring and simple)

if you need a video, I might be able to send one via discord :)

**Comment by dawson-vilamaa** [comment]
We have resolved this issue over Discord. It seemed to solve itself, but I have implemented something to prevent something like this happening which will be included in the next release.
