### ISSUE TITLE
Support 1.19.4

### ISSUE THREAD

**Issue by DmitryASmith** [dawson-vilamaa/BeaconWaypoints#14]
Thank you for developing.
If possible, add support for SpyGot 1.19.4. I haven't downloaded your code (I'm still a long way from developing in java). I tried to redefine the dependencies for the classes, but it looks like something has changed in the queries. I attach a log of startup errors.

> 
[crashWP161.txt](https://github.com/dawson-vilamaa/BeaconWaypoints/files/11023729/crashWP161.txt)
__________
I want to add that I still got into the decompiler: It is enough to add a class and change calls to the API and everything works on 1.19.4. Thank you for the clear code, even when decompiled, everything is quite easy to read. You are super! But please add support to the official repository.

**Comment by mattheweddy** [comment]
@DmitryASmith 

Could you fork the repo for your working version (for 1.19.4)? I’m not having any luck with copying/editing the 1_19_R2 class and recompiling.

**Comment by DmitryASmith** [comment]
With the permission of the author. So that there are no more questions for me, I will post here a working version with my additions to support 1.19.4 (since I did not use the source codes). 

Rename the file to jar...
[BeaconWaypoints-1.6.1b2.jar.zip](https://github.com/dawson-vilamaa/BeaconWaypoints/files/11154270/BeaconWaypoints-1.6.1b2.jar.zip)
