### ISSUE TITLE
📢More Permission❗

### ISSUE THREAD

**Issue by tons4070** [dawson-vilamaa/BeaconWaypoints#3]
👍This plugin is really cool and I really like it. So I wanted to help with something I could do. So, I then used this plugin and found some problems and wanted to help solve various problems of this plugin or help offer new functions about this plugin.

My problem is When I deploy this plugin on my server with many players. I would like some players with permission to use this only. But I was disappointed to find that it couldn't do that.

So I would like to suggest that in the next update there should be more permissions.

For example: 
1. Creating public waypoints is for admins only and normal players cannot delete them. 
2. Beacons can only be used by people with permission.
3. Can disable players from creating private waypoints or require permission

Finally, I appreciate creating this cool plugin, and I hope my problem or offer will be resolved soon.

Thank you. 💗🙇‍♀

**Comment by dawson-vilamaa** [comment]
Thank you for providing feedback! I can definitely add some config options to make it easier for admins for manage. Currently, there's a permission for using the waypoint command (I believe it's BewconWaypoints.waypoint). I will probably add a "delete waypoint" permission to prevent those without it from breaking beacons if it has any waypoints attached, a "use waypoints" permission, and a "use private waypoints" permission for creating and teleporting to private waypoints. Let me know if this is good or needs improvement.

**Comment by tons4070** [comment]
> Thank you for providing feedback! I can definitely add some config options to make it easier for admins for manage. Currently, there's a permission for using the waypoint command (I believe it's BeaconWaypoints.waypoint). I will probably add a "delete waypoint" permission to prevent those without it from breaking beacons if it has any waypoints attached, a "use waypoints" permission, and a "use private waypoints" permission for creating and teleporting to private waypoints. Let me know if this is good or needs improvement.

Yes, it's good. add a "use waypoint" permission and a "use private waypoint" permission.

Now I know "BeaconWaypoints.waypoint" permission is available, but I can't use it. I'm not sure what caused it, but I'm going to try restaturing my server again, probably because I'm using version 1.18.2.

**Comment by dawson-vilamaa** [comment]
I will work on adding new config options and permissions, and I should have an update out by this weekend.

**Comment by dawson-vilamaa** [comment]
Version 1.3.0 has been release which includes a rework of permissions suggested here.

**Comment by tons4070** [comment]
> Version 1.3.0 has been release which includes a rework of permissions suggested here.

Yeah, I can see that.
I appreciate creating such a good plugin and I will definitely continue to support you in the future.

Thank you. &d<3
