### ISSUE TITLE
the player does not teleport between points.

### ISSUE THREAD

**Issue by Chypik** [dawson-vilamaa/BeaconWaypoints#4]
Paper version git-Paper-274 (MC: 1.18.2)
[BeaconWaypoints] Enabling BeaconWaypoints v1.3.0

problem:
the player does not teleport between points. It takes off but comes back. The operator with OP rights moves without problems.
parameter set for the player: BeaconWaypoints.useWaypoints

**Comment by dawson-vilamaa** [comment]
This issue has been fixed in version 1.3.1 by adding compatibility with NoCheatPlus.
