### ISSUE TITLE
Wrong available update message.

### ISSUE THREAD

**Issue by meyverick** [dawson-vilamaa/BeaconWaypoints#5]
**Describe the bug**
Shows available update while I'm already using the 1.3.2 version.

**To Reproduce**
Download latest version on [Spigot](https://www.spigotmc.org/resources/beaconwaypoints.99866/).

**Expected behavior**
Don't show the message.

**Screenshots**
```
A new version of Beacon Waypoints is available!
[Current](http://www.google.com/search?hl=en&q=allinurl%3Adocs.oracle.com+javase+docs+api+current) version: 1.3.0
Updated version: 1.3.2
Download link: https://www.spigotmc.org/resources/beaconwaypoints.99866
```

**Minecraft Server:**
- Edition: Purpur 1.18.2
- Plug-ins:
  - BeaconWaypoints-1.3.2.jar
  - Chunky-1.2.164.jar
  - ChunkyBorder-1.0.64.jar
  - EnchantmentDisbler BETA 0.1.3.jar
  - finiteNetherite-1.0.jar
  - FortressPlugin-v1.0.2-1.18.2.jar
  - LuckPerms-Bukkit-5.4.21.jar
  - SmartItemSort.jar
  - XPDeathDropFix-1.0.1.jar

**Comment by dawson-vilamaa** [comment]
This was fixed in version 1.4.0
