### ISSUE TITLE
Beacons can be taken out of the menu by players

### ISSUE THREAD

**Issue by Agnet75** [dawson-vilamaa/BeaconWaypoints#6]
**Describe the bug**
People can pick up beacons out from the "Change beacon effect"

**To Reproduce**
1. Go to a beacon waypoint
2. Click on the "Change beacon effect" icon
3. Pick it up into your inventory
4. Get a free beacon

**Expected behavior**
It should either not let people grab them, or at least disappear the items from their inventory when closing the menu

**Screenshots**
I don't have screenshots but I have the error logs of what is happening in console:

https://pastebin.com/4C25SYyP 

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser: Vivaldi
 - Version: 22

**Additional context**
Nothing else that I can think of.

**Comment by dawson-vilamaa** [comment]
Mojang's update replaced for 1.19.1 replaced 1_19_R1 rather than creating 1_19_R2 for NMS, and because of this, the plugin can only support either 1.19 or 1.19.1 and 1.19.2. You will either have to use version 1.4.0 or update the server. (This was resolved via Discord)
